### ISSUE TITLE
Question: Nested Documents

### ISSUE THREAD

**Issue by nvella88** [alexandre-spieser/mongodb-generic-repository#11]
When you have nested documents, should both classes implement IDocument? Do you need to set the BsonId for the ID property of the nested object?

**Comment by alexandre-spieser** [comment]
Hi,
only the main document class should implement IDocument, not the nested objects.
For the nested entities you must generate the Ids yourself, the mongodb driver does not seem to populate them by default.

**Comment by nvella88** [comment]
Thank you for your answer, Alexandre.

**Comment by alexandre-spieser** [comment]
No problem.
