### ISSUE TITLE
GetPaginated does not seem to allow for sorting

### ISSUE THREAD

**Issue by hiredgunhouse** [alexandre-spieser/mongodb-generic-repository#13]
It seems that GetPaginated allows only for filtering but not sorting which kinda makes it unusable for typical grid case :/

**Comment by hiredgunhouse** [comment]
Looks good, except for a scenario where you want to sort by multiple columns.
I believe Builders<TDocument>.Sort has a Combine method that can combine multiple sort definitions at least that's what I used.
Probably it would be best to provide an overload takes SortDefinition and show in the docs that you can use that for both single and multiple column sorting scenarios.
Also an overload taking PaginationOptions sound good.

BTW. Thank you for your fantastic work it saved me a ton of time!

**Comment by alexandre-spieser** [comment]
Done.
https://github.com/alexandre-spieser/mongodb-generic-repository/releases/tag/1.3.9
