### ISSUE TITLE
UpdateOneAsync

### ISSUE THREAD

**Issue by dewelloper** [alexandre-spieser/mongodb-generic-repository#15]
How can i use this function

                    bool result = await _mongoDbRepository.UpdateOneAsync<XPartitionedDocument,float>(
                        documentToModify: isExist,
                        field: x => (float)x.TotalPrice,
                        value: td.TotalPrice
                        );
https://stackoverflow.com/questions/54885343/mongodb-updateoneasync-expressionfunction-returning-input-string-was-not-in-a-co

**Comment by alexandre-spieser** [comment]
Seems like you answered your own question in StackOverflow.
