### ISSUE TITLE
Question : How to update more sub documents

### ISSUE THREAD

**Issue by tale07** [alexandre-spieser/mongodb-generic-repository#17]
I have collection which contain array  of another model, and want to update all object in that array or delete them by ID

I want to update all category which id is 1, with this code I can update only first record in array ,
I used [-1] is ,it possible to update more than one item array

`     return await _memoCodeSetRepository.GetAndUpdateOne<MemoCodeSet>(
            Builders<MemoCodeSet>.Filter.Where(x => x.Id == modified.Id && x.MemoCode.Any(i => i.Category.Id == categoryGuid)),
            Builders<MemoCodeSet>.Update.Set(x => x.MemoCode[-1].Category, memoCodeSetCategory),
                    new FindOneAndUpdateOptions<MemoCodeSet, MemoCodeSet> { ReturnDocument = ReturnDocument.After });`

Example

`  {
    "description": "Memo Code Set  Test 2",
    "category": [
      {
        "id": "1",
        "name": "Category Test 1"
      },
      {
        "id": "1",
        "name": "Category Test 1"
      },
      {
        "id": "fb843a50-4b91-44b9-ad9a-6422d4587983",
        "name": "test"
      },
      {
        "id": "ba845800-4aa7-43fa-8e1b-f5759a6bf4de",
        "name": "test 2"
      },
      {
        "id": "f4750605-38ba-4cd3-8cb4-8f7ea9fd6601",
        "name": "dsadsadasdsad"
      }
    ],
    "memoCode": [
      {
        "id": "893f2a78-abf9-46a5-a15e-c613f286939c",
        "category": {
          "id": "e3230886-9df9-473a-b4b9-d933d1dda3a2",
          "name": "Category Test 1"
        },
        "code": "6812",
        "description": "Description 1",
        "overTimeAbsenceCode": "Overtime",
        "exportCode": "23115",
        "categoryName": "Category Test 1"
      },
      {
        "id": "18055ffb-69f6-4aea-8934-3b16d396b462",
        "category": {
          "id": "d19270ec-41f9-4afe-bf3a-4542512a8dc0",
          "name": "Category Test 2"
        },
        "code": "2341",
        "description": "Description 2",
        "overTimeAbsenceCode": "Absence",
        "exportCode": "6513",
        "categoryName": "Category Test 2"
      }
    ],
    "copyMemoCodeSetId": null,
    "id": "e5aca50a-5032-4fd3-ac4f-5ad328fadbf7",
    "addedAtUtc": "2019-03-14T15:06:31.281Z",
    "version": 0
  }`

**Comment by alexandre-spieser** [comment]
Hey, Thanks for your message.
I have had a quick look and found this on the web:
https://stackoverflow.com/questions/31453681/mongo-update-array-element-net-driver-2-0
```
public void UpdateItemTitle(string agendaId, string itemId, string title){
    var filter = Builders<TempAgenda>.Filter.Where(x => x.AgendaId == agendaId && x.Items.Any(i => i.Id == itemId));
    var update = Builders<TempAgenda>.Update.Set(x => x.Items[-1].Title, title);
    var result = _collection.UpdateOneAsync(filter, update).Result;
}
```
which seems to work with [-1].
Have you tried to do this operation with UpdateOneAsync instead of the GetAndUpdateOne?
I am not modifying anything in terms of driver behaviour, so if this does not work there is not much I can do I'm afraid.
