### ISSUE TITLE
 MongoDB stored procedure

### ISSUE THREAD

**Issue by ahmad4it** [alexandre-spieser/mongodb-generic-repository#25]
Hi Alexandre,

How to create MongoDB stored procedure or calling a Stored Procedure in MongoDB via "mongodb-generic-repository" ?

**Comment by alexandre-spieser** [comment]
Not sure if you can add through the driver, I have not used this feature before.
However you can try to call a function using the following code: (untested, just looked at https://stackoverflow.com/questions/23709351/calling-a-stored-procedure-in-mongodb-via-c-sharp)

```
public class TestRepository : BaseMongoRepository, ITestRepository
{
        public void MyCustomFunction()
        {
            var command = new JsonCommand<BsonDocument>($"{{ eval: \"addNumbers({1},{2})\" }}");
            var result = MongoDbContext.Database.RunCommand(command)["retval"].ToInt32();
            BsonValue bv = test.Eval("myAddFunction");
            BsonValue bv1 = test.Eval(bv.AsBsonJavaScript.Code, 1, 2);
        }
        ......
}
```

Good luck
