### ISSUE TITLE
Is Upsert Possible?

### ISSUE THREAD

**Issue by TraGicCode** [alexandre-spieser/mongodb-generic-repository#28]
Hey,

Is Upsert possible on the repository currently?  For Example, if i want to allow a single method to be called for both inserts AND updates?  I tried using `.UpdateOne()` but that seems to not do this.

**Comment by alexandre-spieser** [comment]
Hello, no but you can easily implement your custom behaviour in a class repo inheriting from `BaseMongoRepository`, where the `MongoDbContext` gives you access to raw driver capabilities.

**Comment by TraGicCode** [comment]
Thanks @alexandre-spieser

**Comment by H-Finch-404** [comment]
Is still this the case right now? If not, would you consider adding it to the library? Upsert is a pretty basic MongoDB/document db feature
