### ISSUE TITLE
Remove code that modified global MongoDB Driver Settings

### ISSUE THREAD

**Issue by TraGicCode** [alexandre-spieser/mongodb-generic-repository#29]
We just hit a pretty big production issue today would love to request a change to your library.

Essentially, we have data access code that is not utilizing this packages repository classes ( and i'm sure other consumers would as well especially if they are following a strict form of CQRS ).  Unfortunately, The default settings for the mongodb C# client is to use LegacyUUID.  Unfortunately, as soon as an implementation of our repository gets instantiated the below lines of code is GLOBALLY changing the driver settings mid application run.

https://github.com/alexandre-spieser/mongodb-generic-repository/blob/7a82a281fb1fe79dc342a6383f083c5a2bf11526/MongoDbGenericRepository/MongoDbContext.cs#L117

Is this a requirement for your library to work correctly?  This is just a bad practice in general as it causes mongodb C# driver ( hence the application ) to start behaving differently mid application run.  In our case, we were creating user sessions using the legacy uuid default and when our repository got instantiated the updating/reading of sessions created with LegacyUUID started failing preventing customers from checking out.

**Comment by alexandre-spieser** [comment]
Raised and solved here:

https://github.com/alexandre-spieser/mongodb-generic-repository/issues/7

+ You can override the GuidRepresentation with `MongoDbContext.SetGuidRepresentation()`.
+ Or simply inherit from MongoDbContext and override the constructor defaults.

**Comment by TraGicCode** [comment]
Hey @alexandre-spieser ,

Can you please explain why this change is needed within your MongoDbContext class?  I still feel like this should be the responsibility of the application to decide how mongodb should behave at a global level

**Comment by alexandre-spieser** [comment]
You can make this change in the constructor of your repository, as shown above. It is not needed to to do anything within the MongoDBContext.
The legacy UUID is a famous issue that becomes a big blocker when programmes written in different languages are accessing the same documents with UUID fields. 
It is strongly recommended to avoid the legacy subtype 3 whenever possible. 
I chose to make this by default to apply best practices from the beginning.
