### ISSUE TITLE
Add UpdateMany() method to IBaseMongoRepository_Update

### ISSUE THREAD

**Issue by TraGicCode** [alexandre-spieser/mongodb-generic-repository#30]
I would be nice to be able to utilize UpdateMany() on the base class just like AddMany()

**Comment by alexandre-spieser** [comment]
Hello, thanks for the message.
Things are hectic at the moment but yeah, it's possible :)
Do you already have a suggested implementation you'd like to contribute?

**Comment by TraGicCode** [comment]
> Hello, thanks for the message.
> Things are hectic at the moment but yeah, it's possible :)
> Do you already have a suggested implementation you'd like to contribute?

Hey Alexandre,

I'm busy as well unfortunately. I would assume it would be similiar to how AddMany was done.

**Comment by alexandre-spieser** [comment]
Finally got the time for this!

https://github.com/alexandre-spieser/mongodb-generic-repository/releases/tag/1.4.4

**Comment by TraGicCode** [comment]
Hey @alexandre-spieser ,

You are awesome :D.  Thanks for doing this.

**Comment by alexandre-spieser** [comment]
@TraGicCode No worries, sorry it took so long, COVID-19 crisis did not help... Hopefully it does the stuff you need!
FYI, I pushed version 1.4.5 this morning, which removed the `new UpdateOptions { IsUpsert = true }` default argument in update methods, to avoid unexpected document insertions.

More info here : https://github.com/alexandre-spieser/mongodb-generic-repository/releases/tag/1.4.5
