### ISSUE TITLE
The CancellationToken class needs to be supported in CRUD methods

### ISSUE THREAD

**Issue by ghost** [alexandre-spieser/mongodb-generic-repository#36]
I see in MongoDB there is asynchronous support. However when you build this Repo Generic I did not find the CRUD methods using the CancellationToken class. If my understanding is limited, please ignore it

**Comment by alexandre-spieser** [comment]
Yeah you're right I did not include the CancellationToken. It's a personal choice, I never used it.

**Comment by mincasoft** [comment]
Please use Cancellation as a parameter with default
Ex: Task<TDocument> AddOneAsync<TDocument>(TDocument doc, ..., CancellationToken = default)
I am very grateful for that

**Comment by benzara-tahar** [comment]
any news  about the CancelationToken support  in the future?

**Comment by alexandre-spieser** [comment]
Done in https://github.com/alexandre-spieser/mongodb-generic-repository/releases/tag/1.4.7 let mew know if I've missed some.

**Comment by alexandre-spieser** [comment]
Cancellation Token should now be supported on all methods https://github.com/alexandre-spieser/mongodb-generic-repository/releases/tag/1.5.0
