### ISSUE TITLE
Is it possible to use with .Net 4.8?

### ISSUE THREAD

**Issue by marciliooliveira** [alexandre-spieser/mongodb-generic-repository#41]
Hi, 

Is it possible to use with .Net 4.8? I'm having some issues trying to run it mainly with libzstd.dll because when I installed using nuget it's putting as a content in my solution.

Thanks.

**Comment by alexandre-spieser** [comment]
Hello, I have not tried it, please let me know if there are any issues.
The lib being downloaded as content as because of the latest MongoDB driver, it's pulling a bunch of dependencies to the project via nuget.
