### ISSUE TITLE
CosmosDB UUID issue

### ISSUE THREAD

**Issue by deus42** [alexandre-spieser/mongodb-generic-repository#7]
Hi,

I'm currently facing issue with UUID 04 representation in CosmosDB mongo API driver:

`"Message": "GuidRepresentation Standard is only valid with subType UuidStandard, not with subType UuidLegacy.\r\nИмя параметра: guidRepresentation"`

They said they added it to all regions: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/20206180-support-uuid-subtype-4

I just wonder how to make it work both MongoDB and CosmosDB with Standard UUID type?

Seems to me that only CSharpLegacy type will work for both. Any suggestions?

**Comment by alexandre-spieser** [comment]
Hello, 

The IMongoDbContext of the repositroy exposes the following method:

```
        /// <summary>
        /// Sets the Guid representation of the MongoDb Driver.
        /// </summary>
        /// <param name="guidRepresentation">The new value of the GuidRepresentation</param>
        void SetGuidRepresentation(MongoDB.Bson.GuidRepresentation guidRepresentation);
```
Allowing you set the guidRepresentation to whatever is needed for your application.

**Comment by deus42** [comment]
Yes, it is [a bug in CosmosDB](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/32109040-uuid-type-4-cosmosdb-support-uuidstandard). I got rid of your repository (because of the static constructor) and use CSharpLegacy type. Otherwise, it won't work. I encourage you to remove the static constructor.

**Comment by alexandre-spieser** [comment]
Thanks for the feedback, I'll look into removing the static constructor. 
I have not tested this, but are you sure you cannot overwrite the GuidRepresentation in the constructor of your repository though?

```
        public TestRepository(string connectionString, string databaseName) : base(connectionString, databaseName)
        {
              MongoDbContext.SetGuidRepresentation(MongoDB.Bson.GuidRepresentation.CSharpLegacy);
        }
```

**Comment by deus42** [comment]
It is not causing an issue with MongoDB, but rather with CosmosDB with mongo wire protocol.

**Comment by StephenStrickland** [comment]
Using `MongoDbContext.SetGuidRepresentation()` fixes the problem.

**Comment by alexandre-spieser** [comment]
yeah it does. I've also removed the static constructor in the last version of the repo ;)

**Comment by abstracthuman** [comment]
I'm still having some trouble getting this to work with Azuer Cosmos DB. Could someone please elaborate a bit on where I need to instantiate this override and/or what the Startup code for Identity should look like? I was seeing you can change **public class ApplicationUser : MongoIdentityUser<Guid>** to use **<ObjectId>**, but then **AddMongoDbStores** won't accept anything but **Guid**.

**Comment by abstracthuman** [comment]
I'm still having trouble with this and can't seem to get the document records to show up in Azure Cosmos DB. Could you please elaborate on how the override is used and where it needs to be instantiated? Also, do I need to make some changes to the Startup or anything around the Document to associate to the user?

**Comment by pfekrati** [comment]
I also can't get the docs to show up in CosmosDB. I'm getting this error: "Error querying documents: The GuidRepresentation for the reader is CSharpLegacy, which requires the binary sub type to be UuidLegacy, not UuidStandard"

I tried below code, but it's not working:

    public class MongoDbRepository : BaseMongoRepository, IDocumentDbRepository
    {
        public MongoDbRepository(string connectionString, string databaseName) : base(connectionString, databaseName)
        {
            MongoDbContext.SetGuidRepresentation(MongoDB.Bson.GuidRepresentation.CSharpLegacy);
        }
    }
