### ISSUE TITLE
Save documents of the same type into different collections

### ISSUE THREAD

**Issue by artemiusgreat** [alexandre-spieser/mongodb-generic-repository#8]
Hi, thank you for the nice library, I have a question though. 
Is it possible to save documents of the same type into different tables / collections depending on some property?

**Example**

```
class Fruit : Document 
{
  string Name { get; set; }
}

var pears = new List<Fruit>(); 
var apples = new List<Fruit>(); 

pears.Add(new Fruit { Name = "Pear 1" }); 
pears.Add(new Fruit { Name = "Pear 2" }); 

apples.Add(new Fruit { Name = "Apple 1" });
apples.Add(new Fruit { Name = "Apple 2" }); 

repository.AddManyAsync<Fruit>(pears);
repository.AddManyAsync<Fruit>(apples);
```

By default both, apples and pears, will be saved to collection **Fruits**. 
Is it possible to save apples as **Apples** and pears as **Pears**? 

I see that it's possible to add some prefix to a collection if I add documents one by one. 
https://github.com/alexandre-spieser/mongodb-generic-repository#partitioned-collections 

```
var apple = new Apple("Apple");
repository.AddOne(apple); 
```

Is it possible to do this for more than one document, e.g. for the List<Document>?

**Comment by artemiusgreat** [comment]
Figured this out. Created method that works as AddManyAsync but uses GetCollection directly instead of HandlePartitioned. In this case we can specify different collection in Mongo DB for the same model / class / type in C#. 

```
public class CStorage<T> : BaseMongoRepository, IStorageService<T>
{
  public CStorage() : base(
    ConfigurationManager.AppSettings["MongoConnection"],
    ConfigurationManager.AppSettings["MongoStorage"])
  {
  }

  public async Task AddPartitionsAsync<TDocument>(IEnumerable<TDocument> documents, string partitionKey = null) where TDocument : IDocument
  {
    if (documents.Any())
    {
      documents.ForEach(o => FormatDocument(o));

      if (string.IsNullOrEmpty(partitionKey))
      {
        await GetCollection<TDocument>().InsertManyAsync(documents);
      }

      await GetCollection<TDocument>(partitionKey).InsertManyAsync(documents);
    }
  }
}
```

**Comment by alexandre-spieser** [comment]
Glad you solved your issue :)

Yes AddMany does not support insertion of documents with different `PartitionKey` values.

You could however try:

```
            foreach(var group in documents.GroupBy(e => e.PartitionKey))
            {
                repo.AddMany<DocType, TKey>(group);
            }
```
I have not tested this but it should theoretically work.
That way you can not mistakenly insert docs in the wrong partition.

**Comment by alexandre-spieser** [comment]
The next release will do this natively:

https://github.com/alexandre-spieser/mongodb-generic-repository/commit/7f126a098da5aa30571bed043b9d03f8492bc8c1
