### ISSUE TITLE
How to Connect On MongoDB Atlas?

### ISSUE THREAD

**Issue by samuelrochaoliveira** [alexandre-spieser/mongodb-generic-repository#9]
Hi @alexandre-spieser,

How do I report the security protocol in connection with the mongodb atlas? Like this:

![image](https://user-images.githubusercontent.com/15462690/47518948-b92e1600-d862-11e8-9372-464d5b236186.png)

Your implementation at [MongoDbContext](https://github.com/alexandre-spieser/mongodb-generic-repository/blob/master/MongoDbGenericRepository/MongoDbContext.cs), line 47:

![image](https://user-images.githubusercontent.com/15462690/47518906-926fdf80-d862-11e8-9feb-782eef136dea.png)

Thanks. o/

**Comment by alexandre-spieser** [comment]
Hi, sorry I was on holiday with limited internet access.
Did you sort out your issue?

**Comment by aldrouin** [comment]
Yes

**Comment by samuelrochaoliveira** [comment]
Hi @alexandre-spieser 

Yes. Thanks. 

Now I will open another issue but on another subject. :)
